# **Data Cleaning & Preprocessing**

The Ecommerce Customer Churn dataset contains missing values, duplicate records, inconsistent values, and categorical variables that must be cleaned before building machine learning models.

The objectives of this stage are:

* Handle missing values
* Remove duplicate records
* Fix inconsistent values
* Convert data types where required
* Encode categorical variables
* Prepare the dataset for machine learning

## **Load DataSet**

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv(r"C:\Users\user\Desktop\Machien learning Project\Data\ecommerce_customer_churn_dataset.csv")
df.head()

,Age,Gender,Country,City,Membership_Years,Login_Frequency,Session_Duration_Avg,Pages_Per_Session,Cart_Abandonment_Rate,Wishlist_Items,...,Email_Open_Rate,Customer_Service_Calls,Product_Reviews_Written,Social_Media_Engagement_Score,Mobile_App_Usage,Payment_Method_Diversity,Lifetime_Value,Credit_Balance,Churned,Signup_Quarter
0,43.0,Male,France,Marseille,2.9,14.0,27.4,6.0,50.6,3.0,...,17.9,9.0,4.0,16.3,20.8,1.0,953.33,2278.0,0,Q1
1,36.0,Male,UK,Manchester,1.6,15.0,42.7,10.3,37.7,1.0,...,42.8,7.0,3.0,NaN,23.3,3.0,1067.47,3028.0,0,Q4
2,45.0,Female,Canada,Vancouver,2.9,10.0,24.8,1.6,70.9,1.0,...,0.0,4.0,1.0,NaN,8.8,NaN,1289.75,2317.0,0,Q4
3,56.0,Female,USA,New York,2.6,10.0,38.4,14.8,41.7,9.0,...,41.4,2.0,5.0,85.9,31.0,3.0,2340.92,2674.0,0,Q1
4,35.0,Male,India,Delhi,3.1,29.0,51.4,NaN,19.1,9.0,...,37.9,1.0,11.0,83.0,50.4,4.0,3041.29,5354.0,0,Q4

## **Checking Missing Values**

In [3]:

df.isnull().sum().sort_values(ascending=False)

Social_Media_Engagement_Score    6000
Credit_Balance                   5500
Mobile_App_Usage                 5000
Returns_Rate                     4491
Wishlist_Items                   4000
Discount_Usage_Rate              3500
Product_Reviews_Written          3500
Session_Duration_Avg             3399
Days_Since_Last_Purchase         3000
Pages_Per_Session                3000
Email_Open_Rate                  2528
Payment_Method_Diversity         2500
Age                              2495
Customer_Service_Calls            168
Gender                              0
Average_Order_Value                 0
Total_Purchases                     0
Cart_Abandonment_Rate               0
Login_Frequency                     0
Membership_Years                    0
City                                0
Lifetime_Value                      0
Country                             0
Churned                             0
Signup_Quarter                      0
dtype: int64

## **Handle Missing Values**

#### Fill Missing Numerical Values with Median

In [4]:
num_cols = df.select_dtypes(include=['number']).columns

for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

#### Fill Missing Categorical Values with Mode

In [5]:
cat_cols = df.select_dtypes(include='object').columns

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

The dataset contains missing values in both numerical and categorical columns. 

Missing numerical values were replaced using the median, and missing categorical values were replaced using the mode to preserve the dataset for further analysis.

## **Verifying Missing Values**

In [6]:
df.isnull().sum().sort_values(ascending=False)

Age                              0
Discount_Usage_Rate              0
Churned                          0
Credit_Balance                   0
Lifetime_Value                   0
Payment_Method_Diversity         0
Mobile_App_Usage                 0
Social_Media_Engagement_Score    0
Product_Reviews_Written          0
Customer_Service_Calls           0
Email_Open_Rate                  0
Returns_Rate                     0
Days_Since_Last_Purchase         0
Gender                           0
Average_Order_Value              0
Total_Purchases                  0
Wishlist_Items                   0
Cart_Abandonment_Rate            0
Pages_Per_Session                0
Session_Duration_Avg             0
Login_Frequency                  0
Membership_Years                 0
City                             0
Country                          0
Signup_Quarter                   0
dtype: int64

### Missing Value Treatment

The following actions were taken:

* Missing numerical values were filled using the median of each column.
* Missing categorical values were filled using the mode.
* After preprocessing, all missing values were successfully removed.
* These steps help maintain data quality and prepare the dataset for machine learning.

## **Check Duplicate Records**

In [7]:
df.duplicated().sum()

np.int64(0)

## **Removing Duplicates**

In [8]:
df.drop_duplicates(inplace=True)
df.duplicated().sum()

np.int64(0)

## **Outlier Detection And Removing**

In [9]:
outlier_columns = ['Churned', 'Membership_Years']

for col in outlier_columns:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - (1.5 * IQR)
    upper_bound = Q3 + (1.5 * IQR)

    df = df[
        (df[col] >= lower_bound) &
        (df[col] <= upper_bound)
    ]

## **Fix Inconsistent Values**

In [10]:
df[(df["Total_Purchases"] == 0) &
   (df["Average_Order_Value"] > 0)].shape

(9, 25)

In [11]:
df = df[~(
    (df["Total_Purchases"] == 0) &
    (df["Average_Order_Value"] > 0)
)]

## **Convert Data Types**

### **Check Data Types**

In [12]:
df.dtypes

Age                              float64
Gender                            object
Country                           object
City                              object
Membership_Years                 float64
Login_Frequency                  float64
Session_Duration_Avg             float64
Pages_Per_Session                float64
Cart_Abandonment_Rate            float64
Wishlist_Items                   float64
Total_Purchases                  float64
Average_Order_Value              float64
Days_Since_Last_Purchase         float64
Discount_Usage_Rate              float64
Returns_Rate                     float64
Email_Open_Rate                  float64
Customer_Service_Calls           float64
Product_Reviews_Written          float64
Social_Media_Engagement_Score    float64
Mobile_App_Usage                 float64
Payment_Method_Diversity         float64
Lifetime_Value                   float64
Credit_Balance                   float64
Churned                            int64
Signup_Quarter                    object
dtype: object

## **Convert Numerical Columns to Integer**

In [13]:
int_cols = [
    "Age",
    "Membership_Years",
    "Login_Frequency",
    "Wishlist_Items",
    "Total_Purchases",
    "Customer_Service_Calls",
    "Product_Reviews_Written",
    "Mobile_App_Usage",
    "Lifetime_Value",
    "Credit_Balance"
]

for col in int_cols:
    df[col] = df[col].astype(int)

df.dtypes

Age                                int64
Gender                            object
Country                           object
City                              object
Membership_Years                   int64
Login_Frequency                    int64
Session_Duration_Avg             float64
Pages_Per_Session                float64
Cart_Abandonment_Rate            float64
Wishlist_Items                     int64
Total_Purchases                    int64
Average_Order_Value              float64
Days_Since_Last_Purchase         float64
Discount_Usage_Rate              float64
Returns_Rate                     float64
Email_Open_Rate                  float64
Customer_Service_Calls             int64
Product_Reviews_Written            int64
Social_Media_Engagement_Score    float64
Mobile_App_Usage                   int64
Payment_Method_Diversity         float64
Lifetime_Value                     int64
Credit_Balance                     int64
Churned                            int64
Signup_Quarter                    object
dtype: object

## **Categorical Columns**

In [14]:
cat_cols = ["Gender", "Country", "City", "Signup_Quarter"]

for col in cat_cols:
    df[col] = df[col].astype("category")

df.dtypes

Age                                 int64
Gender                           category
Country                          category
City                             category
Membership_Years                    int64
Login_Frequency                     int64
Session_Duration_Avg              float64
Pages_Per_Session                 float64
Cart_Abandonment_Rate             float64
Wishlist_Items                      int64
Total_Purchases                     int64
Average_Order_Value               float64
Days_Since_Last_Purchase          float64
Discount_Usage_Rate               float64
Returns_Rate                      float64
Email_Open_Rate                   float64
Customer_Service_Calls              int64
Product_Reviews_Written             int64
Social_Media_Engagement_Score     float64
Mobile_App_Usage                    int64
Payment_Method_Diversity          float64
Lifetime_Value                      int64
Credit_Balance                      int64
Churned                             int64
Signup_Quarter                   category
dtype: object

## **Check Cardinality Before Encoding**

In [15]:
categorical_columns = ['Gender', 'Country', 'City', 'Signup_Quarter']

for col in categorical_columns:
    print(col, ":", df[col].nunique())

Gender : 3
Country : 8
City : 40
Signup_Quarter : 4

## **Label Encoding**

In [16]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

cols_to_encode = ['Country', 'City', 'Signup_Quarter']

for col in cols_to_encode:
    df[col] = le.fit_transform(df[col].astype(str))

df[cols_to_encode].head()
df

,Age,Gender,Country,City,Membership_Years,Login_Frequency,Session_Duration_Avg,Pages_Per_Session,Cart_Abandonment_Rate,Wishlist_Items,...,Email_Open_Rate,Customer_Service_Calls,Product_Reviews_Written,Social_Media_Engagement_Score,Mobile_App_Usage,Payment_Method_Diversity,Lifetime_Value,Credit_Balance,Churned,Signup_Quarter
0,43,Male,2,21,2,14,27.4,6.0,50.6,3,...,17.9,9,4,16.3,20,1.0,953,2278,0,0
1,36,Male,6,20,1,15,42.7,10.3,37.7,1,...,42.8,7,3,27.6,23,3.0,1067,3028,0,3
2,45,Female,1,38,2,10,24.8,1.6,70.9,1,...,0.0,4,1,27.6,8,2.0,1289,2317,0,3
3,56,Female,7,27,2,10,38.4,14.8,41.7,9,...,41.4,2,5,85.9,31,3.0,2340,2674,0,0
4,35,Male,4,9,3,29,51.4,8.4,19.1,9,...,37.9,1,11,83.0,50,4.0,3041,5354,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49994,18,Female,2,19,4,8,21.0,8.4,69.5,3,...,17.4,6,5,15.4,14,2.0,813,3565,1,1
49996,37,Male,7,7,1,21,32.4,9.6,32.5,2,...,17.6,5,3,38.6,12,4.0,1293,3154,0,2
49997,44,Female,7,33,2,19,40.3,10.4,50.6,1,...,25.2,4,6,59.9,18,1.0,1655,1622,0,0
49998,41,Female,7,7,2,17,29.9,10.1,60.8,1,...,34.6,5,2,27.6,14,3.0,1286,2634,0,1
49999,56,Male,6,16,2,2,18.2,8.4,46.0,0,...,0.0,7,0,0.0,4,1.0,1072,612,0,2

## **One-Hot Encoding**

In [17]:
df= pd.get_dummies(
    df, 
    columns=['Gender'], 
    drop_first=True, 
    dtype=int
)
df.head()

,Age,Country,City,Membership_Years,Login_Frequency,Session_Duration_Avg,Pages_Per_Session,Cart_Abandonment_Rate,Wishlist_Items,Total_Purchases,...,Product_Reviews_Written,Social_Media_Engagement_Score,Mobile_App_Usage,Payment_Method_Diversity,Lifetime_Value,Credit_Balance,Churned,Signup_Quarter,Gender_Male,Gender_Other
0,43,2,21,2,14,27.4,6.0,50.6,3,9,...,4,16.3,20,1.0,953,2278,0,0,1,0
1,36,6,20,1,15,42.7,10.3,37.7,1,19,...,3,27.6,23,3.0,1067,3028,0,3,1,0
2,45,1,38,2,10,24.8,1.6,70.9,1,9,...,1,27.6,8,2.0,1289,2317,0,3,0,0
3,56,7,27,2,10,38.4,14.8,41.7,9,15,...,5,85.9,31,3.0,2340,2674,0,0,0,0
4,35,4,9,3,29,51.4,8.4,19.1,9,32,...,11,83.0,50,4.0,3041,5354,0,3,1,0

In [18]:
df.rename(columns={"Gender_Other":"Gender_Female"})

,Age,Country,City,Membership_Years,Login_Frequency,Session_Duration_Avg,Pages_Per_Session,Cart_Abandonment_Rate,Wishlist_Items,Total_Purchases,...,Product_Reviews_Written,Social_Media_Engagement_Score,Mobile_App_Usage,Payment_Method_Diversity,Lifetime_Value,Credit_Balance,Churned,Signup_Quarter,Gender_Male,Gender_Female
0,43,2,21,2,14,27.4,6.0,50.6,3,9,...,4,16.3,20,1.0,953,2278,0,0,1,0
1,36,6,20,1,15,42.7,10.3,37.7,1,19,...,3,27.6,23,3.0,1067,3028,0,3,1,0
2,45,1,38,2,10,24.8,1.6,70.9,1,9,...,1,27.6,8,2.0,1289,2317,0,3,0,0
3,56,7,27,2,10,38.4,14.8,41.7,9,15,...,5,85.9,31,3.0,2340,2674,0,0,0,0
4,35,4,9,3,29,51.4,8.4,19.1,9,32,...,11,83.0,50,4.0,3041,5354,0,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49994,18,2,19,4,8,21.0,8.4,69.5,3,16,...,5,15.4,14,2.0,813,3565,1,1,0,0
49996,37,7,7,1,21,32.4,9.6,32.5,2,15,...,3,38.6,12,4.0,1293,3154,0,2,1,0
49997,44,7,33,2,19,40.3,10.4,50.6,1,12,...,6,59.9,18,1.0,1655,1622,0,0,0,0
49998,41,7,7,2,17,29.9,10.1,60.8,1,12,...,2,27.6,14,3.0,1286,2634,0,1,0,0
49999,56,6,16,2,2,18.2,8.4,46.0,0,9,...,0,0.0,4,1.0,1072,612,0,2,1,0

In [19]:
print("Shape After Cleaning:", df.shape)

Shape After Cleaning: (48410, 26)

In [20]:
df.head()

,Age,Country,City,Membership_Years,Login_Frequency,Session_Duration_Avg,Pages_Per_Session,Cart_Abandonment_Rate,Wishlist_Items,Total_Purchases,...,Product_Reviews_Written,Social_Media_Engagement_Score,Mobile_App_Usage,Payment_Method_Diversity,Lifetime_Value,Credit_Balance,Churned,Signup_Quarter,Gender_Male,Gender_Other
0,43,2,21,2,14,27.4,6.0,50.6,3,9,...,4,16.3,20,1.0,953,2278,0,0,1,0
1,36,6,20,1,15,42.7,10.3,37.7,1,19,...,3,27.6,23,3.0,1067,3028,0,3,1,0
2,45,1,38,2,10,24.8,1.6,70.9,1,9,...,1,27.6,8,2.0,1289,2317,0,3,0,0
3,56,7,27,2,10,38.4,14.8,41.7,9,15,...,5,85.9,31,3.0,2340,2674,0,0,0,0
4,35,4,9,3,29,51.4,8.4,19.1,9,32,...,11,83.0,50,4.0,3041,5354,0,3,1,0

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 48410 entries, 0 to 49999
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Age                            48410 non-null  int64
 1   Country                        48410 non-null  int64
 2   City                           48410 non-null  int64
 3   Membership_Years               48410 non-null  int64
 4   Login_Frequency                48410 non-null  int64
 5   Session_Duration_Avg           48410 non-null  float64
 6   Pages_Per_Session              48410 non-null  float64
 7   Cart_Abandonment_Rate          48410 non-null  float64
 8   Wishlist_Items                 48410 non-null  int64
 9   Total_Purchases                48410 non-null  int64
 10  Average_Order_Value            48410 non-null  float64
 11  Days_Since_Last_Purchase       48410 non-null  float64
 12  Discount_Usage_Rate            48410 non-null  float64
 13  Returns_Rate                   48410 non-null  float64
 14  Email_Open_Rate                48410 non-null  float64
 15  Customer_Service_Calls         48410 non-null  int64
 16  Product_Reviews_Written        48410 non-null  int64
 17  Social_Media_Engagement_Score  48410 non-null  float64
 18  Mobile_App_Usage               48410 non-null  int64
 19  Payment_Method_Diversity       48410 non-null  float64
 20  Lifetime_Value                 48410 non-null  int64
 21  Credit_Balance                 48410 non-null  int64
 22  Churned                        48410 non-null  int64
 23  Signup_Quarter                 48410 non-null  int64
 24  Gender_Male                    48410 non-null  int64
 25  Gender_Other                   48410 non-null  int64
dtypes: float64(10), int64(16)
memory usage: 10.0 MB

In [22]:
save_path = r"C:\Users\user\Desktop\Machien learning Project\Data\ecommerce_customer_churn_Cleanined_day_2.csv"   
df.to_csv(save_path, index=False)
print("Saved Successfully")

Saved Successfully